{% set name = "django-select2" %}
{% set version = "7.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f40ee661377edf493f446c25134e5b53feee17e3bc364a12dac1bf52eabe816a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - pytest-runner
    - sphinx
  run:
    - python >=3.6
    - django >=2.2
    - django-appconf >=0.6.0

test:
  imports:
    - django_select2

about:
  home: https://pypi.org/project/django-select2/
  summary: django-select2, select2 driven Django Widgets.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/codingjoe/django-select2
  doc_url: https://django-select2.readthedocs.io/

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
