{% set name = "django-select2" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2922ff3a7843451fcf529db72f0594824a10dec34cb12d903e32aca642929e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
    - flit >=3.2
    - flit-scm
    - wheel
    - django >=3.2
    - django-appconf >=0.6.0
  run:
    - python >=3.8
    - django >=3.2
    - django-appconf >=0.6.0

test:
  imports:
    - django_select2

about:
  home: https://pypi.org/project/django-select2/
  summary: django-select2, select2 driven Django Widgets.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/codingjoe/django-select2
  doc_url: https://django-select2.readthedocs.io/

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
